version: "3"

services:
  nginx:
    build:
      context: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./services/angular
    ports:
      - 9091:4000
  backend:
    build:
      context: ./services/laravel
    env_file:
      - ./services/laravel/.env.example.docker
    volumes:
      # Enforce "read only" to make sure the app is totally immutable
      - ./services/laravel:/var/www:ro
    ports:
      - 9092:80

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'laravel'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: "redis:alpine"
# Names our volume
volumes:
  mysql_data:
